spring:
  application:
    name: fraud-detection-demo
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.javatechie.serdes.TransactionSerializer
    streams:
      application-id: fraud-detection-streams
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: com.javatechie.serdes.TransactionSerde
      state-dir: /Users/javatechie/Desktop/state